### ISSUE TITLE
No Color Selector in the "logFileHighlighter.customPatterns"

### ISSUE THREAD

**Issue by AlGantori** [emilast/vscode-logfile-highlighter#100]
I get No Color Selector in the "logFileHighlighter.customPatterns" when I hover with the mouse?
The color boxes are displayed and selector pops fine in the "editor.tokenColorCustomizations":  section.  Could this be a VSCode settings bug?

![image](https://user-images.githubusercontent.com/11699920/78290793-25da2500-74d9-11ea-91c6-39c57cca29da.png)

**Comment by emilast** [comment]
Thank you for pointing this it out, I'll investigate if possible to fix.
