### ISSUE TITLE
highlight results in search editor

### ISSUE THREAD

**Issue by AdamSharon** [emilast/vscode-logfile-highlighter#101]
it would be great to see the highlights in the search editor, after opening the search results to the editor.

**Comment by emilast** [comment]
Sorry for the very late reply...

When I just tried it in the latest VS Code , it seems to work correctly:

![image](https://user-images.githubusercontent.com/2369639/87662852-2aaea600-c763-11ea-8cd0-8cebd8c28405.png)

Do you still have problems?

**Comment by AdamSharon** [comment]
thanks for the response. yes, if to be more precise after you comment - i see now that .log files are fine in search editor, but not for .txt files - I have associated .txt files as log in the settings.json.

![image](https://user-images.githubusercontent.com/16919278/87664209-8b42e080-c76d-11ea-99b0-ab974a7ba14c.png)

![image](https://user-images.githubusercontent.com/16919278/87664251-9b5ac000-c76d-11ea-9058-66ec1004e250.png)

**Comment by emilast** [comment]
Yes, I can repeat the problem. It seems to be a bug with the search editor that it doesn't apply custom file associations to the files with search matches. Not much my extension can do about it I'm afraid, but you can always open an issue in the main VS Code repository at https://github.com/microsoft/vscode.

Actually, I found an open issue that might be related: https://github.com/microsoft/vscode/issues/93198
