### ISSUE TITLE
Remote development support?

### ISSUE THREAD

**Issue by tmtom** [emilast/vscode-logfile-highlighter#103]
As I understand this extension works only for local development (can't see option to install it on a remote SSH server).
Would be nice to support remote development.

**Comment by emilast** [comment]
I'm not familiar with the detailed requirements for using VS Code remotely but it seems to work well for me when I connect it to a WSL Linux environment from my Windows machine. I have the extension installed locally on my Windows machine and it's still usable in the WSL environment as you you can see here:

![image](https://user-images.githubusercontent.com/2369639/85465922-a32da700-b5a9-11ea-8210-515357d439e2.png)

As you can see in the image, Log File Highlighter is usable right off the bat for me while some other seems to require installing in the "remote" Linux environment.

Can you give some more detail on your use-case so I can see if there's something I can do to help fix the problem?

**Comment by tmtom** [comment]
Sorry for the delay. I did some tests and:
- local file - working fine
- remote development - WSL - working fine
- remote development - SSH - does not work (the default log highlighter is being used)

I am not sure what is the difference between SSH and WSL fro VScode / extension. Perhaps in WSL its is making use of the fact that via 9p mount it can access the whole filesystem while for SSH everything has to run remotely? Just guessing.

Is there some log VScode log I could collect which might help? Thanks.

**Comment by tmtom** [comment]
I did some more checks and it seems something was high-jacking log file association (I think https://marketplace.visualstudio.com/items?itemName=berublan.vscode-log-viewer which I am also using for SSH remote development). Setting `"*.log": "log"` in the `"files.associations"` fixed that for me and now it is working for me.
Sorry for the false alarm.

**Comment by emilast** [comment]
No worries. Glad to hear it's working!
