### ISSUE TITLE
Output window highlighting

### ISSUE THREAD

**Issue by FasterThanMyShadow** [emilast/vscode-logfile-highlighter#104]
Would it be possible to add the following section to the "contributes/languages/" section in the package.json file? That way text in the output windows are highlighted too.

```
"mimetypes": [
    "log",
    "text/log",
    "text/x-log",
    "text/x-code-output",
    "x-code-output"
]
```

**Comment by emilast** [comment]
Hi,

What is it that is not working without your additions? I just tested opening the output panel and the extension seems to be applied:

![image](https://user-images.githubusercontent.com/2369639/83356439-7ef1f800-a366-11ea-8c4a-d31bfa70a243.png)

**Comment by FasterThanMyShadow** [comment]
That's true for logs, but not e.g. for 'Python Test Log', or 'Remote - SSH'. I think `text/x-code-output` is needed to get those highlighted (at least adding that line to the mimetypes seems to do the trick for me).

**Comment by FasterThanMyShadow** [comment]
Fair enough. Thank you for looking into this and getting back to me.

**Comment by lonix1** [comment]
Is it possible to disable those rules that yield weird results, and keep those that are good? Or are all the regex rules enabled all the time, without possibility of turning them on/off?

This would be a great feature, as the [most popular](https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer) extension for coloring log output is 4 years old without updates. Yours is the best colorizer, just doesn't work on the output window.
