### ISSUE TITLE
Publish extensions to open-vsx

### ISSUE THREAD

**Issue by orblazer** [emilast/vscode-logfile-highlighter#105]
I'm a [VS Codium](https://github.com/VSCodium/vscodium) user, a FLOSS version of VS Code, it's the same code but without the Microsoft's telemetry and branding.
I want to request if possible to add the _Log File Highlighter_ extension on the [open-vsx.org](https://open-vsx.org/) market to us doesn't need to works with the Microsoft marketplace as is unclear if it's legal to use it on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

Additional info:

- This is [how to](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) publish a new extension.

**Comment by HaaLeo** [comment]
I published the extension to the Open VSX Registry [here](https://open-vsx.org/extension/emilast/LogFileHighlighter). Right now everybody can publish to that namespace.

Now it is up to @emilast to [claim his namespace](https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace).

**Comment by HaaLeo** [comment]
Done in eclipse/open-vsx.org#43.

**Comment by emilast** [comment]
I'm closing this now. Feel free to report back if something is not working. I'll publish new versions to open-vsx, as well as to the Visual Studio Code marketplace.
