### ISSUE TITLE
Feature Request - Calculate Time duration on selected Text

### ISSUE THREAD

**Issue by shivan** [emilast/vscode-logfile-highlighter#15]
It would be great, to have a feature to calculate the duration of the selected text...

Example:

I select this:
2016-11-25 12:03:50,659 WARN  [org.pentaho.platform.web.http. ......
.....
....
2016-11-25 12:06:52,859 WARN  [org.pentaho.platform.web.http. ......

Then the tool would show me in the status bar:
Selected: 3 Minutes, 2 Seconds, 200ms

This would be good for performance analysis.

So you have to search the first timestamp text at start of selection and the last one. Then calculate the difference and show it in the status bar.

**Comment by emilast** [comment]
That's a nice idea indeed. I don't have any form of logic in the extension right now but good suggestions like this keep popping up so maybe I should consider taking it to next level and add some interaction. Will consider it, if only I had more time on my hands...
