### ISSUE TITLE
Add highlighting of file system paths

### ISSUE THREAD

**Issue by emilast** [emilast/vscode-logfile-highlighter#20]
Examples:
`C:\foo\bar.txt`
`\\unchost\foo\bar.txt`

**Comment by glen-nicol** [comment]
This does not seem to highlight the entire standard windows paths with backslashes. It will highlight the filename at the very end(sorry it is blurred but you can tell it is blue.).

![image](https://user-images.githubusercontent.com/5103200/36128504-93d79ab6-1017-11e8-8f98-1fc410a1b936.png)

This screenshot is from a log file for another program that has a very similar log format as VS code. So I don't expect it to be supported directly if it does not occur in actual VS code logs. But in that case I would like to know if there is something I can do to get that whole path to highlight.

**Comment by HaaLeo** [comment]
You can wait for the next release of this extension 😊. Path highlighting is not yet included in version 2.0.0 but will be included in the next release.

**Comment by glen-nicol** [comment]
OH! Ha sorry didn't notice that. The readme states it as a feature so I assumed the PR #42 was in the release I got yesterday. Thanks!
