### ISSUE TITLE
tail follow or auto scroll option

### ISSUE THREAD

**Issue by DesHorsley** [emilast/vscode-logfile-highlighter#21]
Hi,

Great extension, I use this every day. Do you think it would be possible to add some functionality to follow a log as its being updated?

Perhaps this can be bound to a short cut to turn the follow on and off.

VS Code already auto updates the file as the log is being written to, the feature would basically keep the view scrolled to the bottom. 

If there were some indication that the file had reloaded that would be fantastic too, perhaps a glyph in the gutter showing the last line when the tab was last active / last being viewed.

**Comment by emilast** [comment]
Thanks, glad you find a use for this little extension.

I actually had the same suggestion from someone else and I can see how it would be useful. I don't have much time to work on this right now I'm afraid (and I don't know exactly how it would be implemented) but I'll keep it in the back of my head and see what I can do later. Or if you could find someone to help, I'll gladly accept a pull request ;-)

I'll leave this issue open until we find a solution.

/Emil

**Comment by HaaLeo** [comment]
I tried to implement the feature [here](https://github.com/HaaLeo/vscode-logfile-highlighter/tree/Enable-Auto-Scrolling). So the scroll function and glyph indication pretty much work.  
But when I went on testing the feature with a real logging engine (I used [winston logger](https://github.com/winstonjs/winston) 2.4.0) I faced the problem that vscode does not update the text document properly (`vscode.workspace.onDidChangeTextDocument` event does not fire). However when I switch between tabs and get back to the log file, that is currently written, the changes are updated once and the glyph is set on the correct position.
For me this seems to be an issue of vscode. Has anybody suggestions how to fix/improve this?  

Here is the `demo-logger.js` script I used for testing:  
```javascript
'use strict';

const logger = require('winston');

logger.configure({
    level: 'debug',
    transports: [
        new logger.transports.File({
            timestamp: true,

            // I guess you need to adjust the filename.
            filename: '../vscode-logfile-highlighter/test/integrationtest/testLogs/thirdLog.log',
            maxFiles: 10,
            tailable: true,
            maxsize: 5000000,
            prettyPrint: true,
            json: false,
            silent: false
        }),
        new logger.transports.Console({
            colorize: true,
            timestamp: true
        })
    ]
});

let count = 1;
let index = 1;
let delay = 1000;
var interval = setInterval(function () {
    if (index === 1) {
        logger.info(' This is the ' + count + '. logging statement.');
    } else if (index === 2) {
        logger.warn(' This is the ' + count + '. logging statement.');
    } else if (index === 3) {
        logger.error('This is the ' + count + '. logging statement.');
    } else if (index === 4) {
        logger.debug('This is the ' + count + '. logging statement.');
        index = 0;
    }
    count++;
    index++;
}, delay);
```

**Comment by emilast** [comment]
Nope, no ideas (haven't really prioritized it, to be honest) but there's another extension which apparently is assumed to do this: https://marketplace.visualstudio.com/items?itemName=fachmann.turbo-log

Worth a look?

**Comment by tiansin** [comment]
@emilast @DesHorsley 
I hope to help you.
https://marketplace.visualstudio.com/items?itemName=tiansin.logtail

**Comment by gschuager** [comment]
You can check out this extension https://marketplace.visualstudio.com/items?itemName=foxx1337.autoscrolldown

**Comment by emilast** [comment]
I will close this issue now, since there seem to exist solutions for this requirement using other extensions.
