### ISSUE TITLE
Git hash is not highlighted properly

### ISSUE THREAD

**Issue by mrvkino** [emilast/vscode-logfile-highlighter#22]
The git hash in my log are not highlighted properly.

I have:
![log](https://cloud.githubusercontent.com/assets/279511/23327722/3531fc70-fadf-11e6-8569-62474320a826.jpeg)

I expect to have the full hash highlighted

**Comment by emilast** [comment]
Thanks for your report. I agree this might be useful and will consider it in the next release.
