### ISSUE TITLE
It does not work for me, it conflict with CMake Tools or CMake Tools Helper

### ISSUE THREAD

**Issue by hyhrob** [emilast/vscode-logfile-highlighter#25]
I tested and found that if I disable the CMake Tools and then reload vscode, the logfile-highlighter can works fine. They all create a toolbar bellow vscode, maybe this lead them conflict each other, I guess.
Hope this information is useful for you.

**Comment by emilast** [comment]
Sorry for the late reply. I see no obvious reason for a conflict with those extensions but have you tried to force log files to be associated with my extension by adding something like this to the user preferences?

```
"files.associations": {
	"*.log": "log"
},
```
That association is already done by the extension but if other extensions have conflicting file associations then it's possible to control what extension handles a given file type using user preferences like this.

**Comment by emilast** [comment]
I'll close this now, feel free to report back if this is still a problem.
