### ISSUE TITLE
constant flashing with long log file

### ISSUE THREAD

**Issue by ypan887** [emilast/vscode-logfile-highlighter#26]
when opened up a long log file (5000line). The log color is flashing between plain and colored. Short logs flash too but only for 2-3 times and it stops.

Version: 1.1.1

changed theme and turn off minimap won't help.

I have add
```
"files.associations": {
	"*.log.*": "log"
}
```
to setting

**Comment by emilast** [comment]
That's strange, I haven't seen that. Do you have many other extensions installed? Have you tried disabling them to see if it improves?

**Comment by emilast** [comment]
The issue have been dormant for several months so I'll close it now.
