### ISSUE TITLE
Not able to enable case insensitive pattern match

### ISSUE THREAD

**Issue by ihatetoregister** [emilast/vscode-logfile-highlighter#276]
A regex with the flag `/i` should match regardless if the string contain upper of lower case letters. However, I am not able to make this work using this extension. Might be me that is just typing it wrong or else it would be good if this could be added. 

**Example input**
Error:

error:

**Patterns**
```
"pattern": "error/i" // not working
"pattern": "error\i" // surprisingly this this matches "error:" but vs code complain about invalid escape char
"pattern": "(?i)error" // "Error message: Regex of custom log message is invalid.
```

Looks like the flags are fixed in the code:
`result.push(new RegExp(pattern, 'gm'));`

**Comment by dev-syn** [comment]
Would be nice to see that regexFlags option implemented trying to use the 's' flag to allow the dot character to represent new lines

**Comment by emilast** [comment]
Finally, I have some news regarding this feature request. In 3.1.0, there is a new option ["patternFlags"](https://github.com/emilast/vscode-logfile-highlighter/tree/3.1.0?tab=readme-ov-file#case-sensitivity) that can be used to make a pattern case insensitive. I hope this helps.
