### ISSUE TITLE
Does not work with large log files

### ISSUE THREAD

**Issue by jake-crane** [emilast/vscode-logfile-highlighter#28]
This doesn't seem to work with large log files.(ex: 200,000 lines) Any chance this will be supported in the future?

**Comment by emilast** [comment]
Can VS Code even open that large files? If it can and my extension is not working then I'm not sure what I could do to make it work.

Of course you can always copy parts of the file into a new buffer and switch to the log file mode (Ctrl + K, M followed by "Log File") but that's a hack of course...

**Comment by jake-crane** [comment]
Yeah, VS Code can open files this large. Maybe the highlighting issue i'm seeing is a limitation of VS Code and not vscode-logfile-highlighter.

**Comment by emilast** [comment]
It seems that they do indeed turn off syntax highlighting for very large files: https://code.visualstudio.com/updates/v1_15#_large-file-support

Unfortunately I have not yet found a setting for changing the size limit so I suppose you'll have to work with smaller files.

**Comment by jake-crane** [comment]
Thank you for looking into this. I guess I'll have to split log files if I want to use syntax highlighting in VS code.
