### ISSUE TITLE
Custome patterns cause memory overflow

### ISSUE THREAD

**Issue by F0ax** [emilast/vscode-logfile-highlighter#286]
I have a custome .log file for which I wanna create highlight patterns.
I played around and experience a memory overflow and extension manager crash, every time I use quantifiers in the regex pattern.

```json
    "logFileHighlighter.customPatterns": [
        {
            "pattern": "test",
            "foreground": "#f0ff00",
            "background": "#000000"
            
        },
        {
            "pattern": "A*",
            "foreground": "#f0ff00",
            "background": "#000000"
            
        }
    ],
```

I use a small logfile with 50 lines for debug.

**The extension manager gives me that:**
![image](https://user-images.githubusercontent.com/80454058/136787840-7eb06cea-15e5-4ae7-aa26-c6570a7bb664.png)

I can see in the ressource manager that my RAM is growing until the extension manager crashes.

Am I using wrong Regex syntax or do I have too little RAM?

**Comment by emilast** [comment]
I'm really sorry to hear this. I suppose there is some change in one of the updated packages. Will investigate to see if I can find the cause of the problem.

Thanks for reporting this.
