### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by uygarp** [emilast/vscode-logfile-highlighter#290]
- Issue Type: `Performance`
- Extension Name: `LogFileHighlighter`
- Extension Version: `2.12.0`
- OS Version: `Linux x64 5.4.0-88-generic`
- VS Code version: `1.61.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/emilast.LogFileHighlighter-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by emilast** [comment]
I'll close this now since no new reports of this problem has been made
