### ISSUE TITLE
Bold Custom Patterns

### ISSUE THREAD

**Issue by SudoWatson** [emilast/vscode-logfile-highlighter#308]
Is there a way to bold a custom pattern? I tried the following but it wouldn't bold the text.
```
"logFileHighlighter.customPatterns": [{
    "pattern": "DBUG",
    "foreground": "#FFF",
    "fontStyle": "bold"
}]
```
also tried
```
"logFileHighlighter.customPatterns": [{
    "pattern": "DBUG",
    "foreground": "#ABB2BF",
    "settings": {
        "fontStyle": "bold"
    }
}]
```
If there's not currently a way, would it be possible to add it?

**Comment by petterssonandreas** [comment]
I was looking for this as well, and looked through the code and looks like it's is not possible right now, but would be very simple to add support for it. The code in question is:

https://github.com/emilast/vscode-logfile-highlighter/blob/master/src/CustomPattern.ts#L17-L21 

I might do a PR for this if I get the time.

**Comment by emilast** [comment]
Thanks, I'll test this and add it if it works.

**Comment by emilast** [comment]
I just release version 2.15 that allows for setting fontWeight on a custom pattern. I got a little carried away and added some other decoration options as well:

https://github.com/emilast/vscode-logfile-highlighter#defining-custom-highlighting-patterns

Here's an example result:
https://github.com/emilast/vscode-logfile-highlighter/blob/master/CHANGELOG.md#2150---12-feb-2022
