### ISSUE TITLE
Unable to match the log level of android

### ISSUE THREAD

**Issue by pengxiaozuo** [emilast/vscode-logfile-highlighter#31]
Unable to match the log level of android.
![image](https://user-images.githubusercontent.com/11833259/31594958-e8a06ae2-b26a-11e7-891f-f4e6c86b0d5a.png)

**Comment by emilast** [comment]
I'm not sure how to interpret your screen shot. What's the log level in this example and how do you expect it to be colored??

**Comment by emilast** [comment]
I think I see it now, it's the `E/`, that indicates an error, isn't it?

**Comment by pengxiaozuo** [comment]
yes, E is error!
