### ISSUE TITLE
Is there any plan for web log?

### ISSUE THREAD

**Issue by wuranxu** [emilast/vscode-logfile-highlighter#315]
👍 I think the extension for vscode is very nice, but sometime I need to highlight my word in web application.

Now I use monaco editor in my application to show log data, I can't highlight it. 😭 

![image](https://user-images.githubusercontent.com/11266738/146663751-66abe485-e633-426a-b0d4-3c783fc280ca.png)

**Comment by emilast** [comment]
I have not investigated how a standalone instance of Monaco works with VS Code extensions so I can't help you out here. A quick googling seems to indicate that it might work but I haven't tried it. Do you see an error message or similar?

**Comment by wuranxu** [comment]
> I have not investigated how a standalone instance of Monaco works with VS Code extensions so I can't help you out here. A quick googling seems to indicate that it might work but I haven't tried it. Do you see an error message or similar?

👌 Thanks a lot!
