### ISSUE TITLE
Adding support for Visual Studio 2017

### ISSUE THREAD

**Issue by DoCode** [emilast/vscode-logfile-highlighter#32]

**Comment by emilast** [comment]
Can you give some more details on this? Do you have an example log that shuld be colored?

**Comment by DoCode** [comment]
I think the add-in should also work in VS 2017.

**Comment by emilast** [comment]
Yes, I can see the point in that, but unfortunately Visual Studio and Visual Studio Code have completely different extension APIs so it would require a complete rewrite of a new extension.
