### ISSUE TITLE
Enhancement Request: Custom log levels

### ISSUE THREAD

**Issue by TotallyInformation** [emilast/vscode-logfile-highlighter#33]
Hi, great extension, thanks for supporting it.

I'm using the NodeJS Winston logging tool and it has some additional logging levels.

It would be great to be able to be able to specify additional log levels and other string tokens. I would, for example, like to be able to colour "Verbose" or "VERBOSE" in green.

**Comment by emilast** [comment]
Yes, that would be useful but I don't know a good way of how to implement that, I'm afraid. I'll keep the issue open though.

**Comment by HaaLeo** [comment]
I will give it a try [here](https://github.com/HaaLeo/vscode-logfile-highlighter/tree/Enable-Custom-Log-Level).
