### ISSUE TITLE
Add new keyword in log level

### ISSUE THREAD

**Issue by Xarkam** [emilast/vscode-logfile-highlighter#34]
Hello,
I do the entity framework and in the log when a sql request fails, the word "Failed" is used.
Would it be possible to add this word into the log level?
Thank you.

**Comment by emilast** [comment]
If you send me a sample (a few lines is enough) from this kind of log, I'll have a look to see how it would fit.

**Comment by Xarkam** [comment]
my code having advanced, I have don't more lines for the moment "failed" in the log of entity framework.
(the log is overwrited at each build)

As soon as I have them again, I put them in this issue.
