### ISSUE TITLE
Defining custom highlighting patterns does not work 

### ISSUE THREAD

**Issue by kiffernase** [emilast/vscode-logfile-highlighter#366]
Hey,

are there any issues known that the custom highlighting does not work anymore?
I tried different statements and none of them seem to work.

``` 
   "logFileHighlighter.customPatterns": [
        {
            "pattern": "0x",
            "foreground": "#c39635",
        },
        {
            "pattern": "Server",
            "foreground": "#c39635",
        },
    ],
```

version 1.67.0
linux  xubuntu18_04

Thanks

**Comment by emilast** [comment]
There are no problems as far as I know. I don't use Linux very much my self but here's an example when using the extension with your config in GitHub codespaces which is Ubuntu-based:

<img width="487" alt="image" src="https://user-images.githubusercontent.com/2369639/169695766-17b65c5b-30d3-41bb-8de6-47be9f0af7cf.png">

**Comment by rcdailey** [comment]
@emilast I'm having this same issue. See here:

```json
  "logFileHighlighter.customPatterns": [
    {
      "pattern": "VRB",
      "foreground": "#aaaaaa" // light gray
    },
    {
      "pattern": "DBG",
      "foreground": "#007acc" // medium blue
    },
    {
      "pattern": "INF",
      "foreground": "#ffffff" // white
    },
    {
      "pattern": "WRN",
      "foreground": "#d7ba7d" // light brownish-yellow
    },
    {
      "pattern": "ERR",
      "foreground": "#af1f1f" // dark red
    }
  ]
```

![image](https://github.com/emilast/vscode-logfile-highlighter/assets/1768054/32885716-aef9-4237-83b7-f1d2cef212e0)

I am using VS Code on Windows 10.

**Comment by emilast** [comment]
I'll have a look if you send me a fragment of (~10 lines or so) of a log file where the custom highlighting doesn't work.

**Comment by rcdailey** [comment]
@emilast Here you go. Thank you!

```txt
[13:06:44 DBG] Processing Sonarr server sonarr_develop
[13:06:44 DBG] HTTP Request: GET http://REDACTED:8990/api/v3/system/status
[13:06:48 DBG] HTTP Response: (No response) GET http://REDACTED:8990/api/v3/system/status
[13:06:48 ERR] Unable to obtain service version information
[13:06:48 ERR] HTTP error: Call failed. No connection could be made because the target machine actively refused it. : GET http://REDACTED:8990/api/v3/system/status
```

**Comment by emilast** [comment]
I've investigated and it does indeed seem like your patterns don't work. It's the brackets in the log file that interfere with the coloring. You can see this if you insert a space after `DBG`, for example. I'll dig a little more into this but for now you can use this small hack with your patterns:

`"pattern": "DBG",` => `"pattern": "DBG(?=.)",`

This uses a positive lookahead expression that the DBG patterns is followed by any character.

**Comment by emilast** [comment]
In 3.0.0 I removed some special handling of custom patterns with only alphanumeric characters that I have to confess I had simply forgot about. 🙄

These patterns should now work as expected without any special treatment.
