### ISSUE TITLE
Doesn't match NLog default log levels

### ISSUE THREAD

**Issue by spaghettidba** [emilast/vscode-logfile-highlighter#37]
![image](https://user-images.githubusercontent.com/7592822/35776587-7f8012f6-099f-11e8-9124-5362180c3799.png)
It seems like the extension matches log levels with a case-sensitive comparison. [Nlog](https://github.com/NLog) instead uses Camelcase log levels, such as "Error", "Info" and so on.

**Comment by weird-dreams** [comment]
So - please add this to the Patterns ;-) 
+ 1

**Comment by emilast** [comment]
Yes, I'm considering it. Will continue discuss it in #37.

**Comment by sm-g** [comment]
@emilast NLog's log-levels usually uppsercased, you need to test not only `Fatal`, but `FATAL` also. At now this uppercased version not highlighted.

**Comment by sm-g** [comment]
And another question - shouldn't `TRACE` be configurable via `"scope": "log.verbose"`?
