### ISSUE TITLE
Regex is not correctly compiled

### ISSUE THREAD

**Issue by danipen** [emilast/vscode-logfile-highlighter#399]
Hi,

I'm maintaining TextMateSharp repository. After update this grammar to the latest changes, there are some patterns that are not correctly compiled by Oniguruma. 

For example, the following regex doesn't compile:

`(?<=^[\\s\\d\\p]*)\\bD\\b`

Just removing `^` or `*`, seems to be valid:
* `(?<=^[\\s\\d\\p])\\bD\\b`
* `(?<=[\\s\\d\\p]*)\\bD\\b`

Could we rewrite the regex to don't have both `^` and `*` at the same time, what seems to be the cause of the issue?

**Comment by danipen** [comment]
Previous working regex was the following one:
`(?<=|[\\s\\d\\p]*)\\bV\\b`

Note that it used `|` instead of `^`.

Not sure if the regex is correct, and I'm using an outdated version of oniguruma library. Some help would be appreciated.

**Comment by emilast** [comment]
The reason there is a `^` in the regexes is to avoid the regexes to match if there are alphanumeric characters before the matching logcat level. If there are, then it's not a logcat log level (as I recall it at least, I'm normally not an Android developer).

If I remove the `^` for the "d" log level, then it's highlighted, which the other log levels are not, in this example:

![image](https://user-images.githubusercontent.com/2369639/185471867-6203b21f-31f0-4d2b-acf9-2c46c6b2e26a.png)

If  you have copied my grammar and want to use it in other editors, then feel free to simplify the regexes to not perform this negative look-behind. This should work:

`<string>\bD\b</string>`

HTH.
