### ISSUE TITLE
Uncolored tokens

### ISSUE THREAD

**Issue by brunolemos** [emilast/vscode-logfile-highlighter#4]
Some colors never show, like the INFO / WARN / ERROR words.

It's probably not understanding info-token / warn-token / error-token anymore. 

PS1: I tried all themes. 
PS2: My log is generated by [winston-logger](https://github.com/winstonjs/winston) for nodejs. But I also tried in your syntax.

Atom One Dark Theme:
![Screenshot - Atom One Dark Theme]
(https://s19.postimg.org/m7tn3r71v/Screen+Shot+2016-04-16+at+9.05.40+PM.png)

Base16 Ocean Dark Theme:
![Screenshot - Base16 Ocean Dark Theme]
(https://s19.postimg.org/kdgsm0k1f/Screen+Shot+2016-04-16+at+8.56.13+PM.png)

**Comment by emilast** [comment]
Hi!

Thanks for reporting this. I'm using **Dark + (default dark)** and have also noticed that the coloring does not seem to work well in all other themes, see #3. Haven't gotten around to fixing it yet though, but your report makes it more likely to happen. :-)

I haven't studied the problem fully yet, but as you say, it seems that `info-token`and the others are not always defined so I have to find an other way of setting the color.

Cheers,

Emil

**Comment by emilast** [comment]
**Update**: The coloring of WARN/ERROR/DEBUG etc fails for my own log files now, after I upgraded to Code 1.0. Will most certainly have to look into this...

**Comment by emilast** [comment]
I just published an updated version 0.7.0 that should fix the problem. Hope this solves your problem :-)

**Comment by brunolemos** [comment]
Kind of...

Isn't there a token that will be red in all themes? The errors are green on the theme I use:
![Atom Dark Theme Screenshot]
(https://s31.postimg.org/5sgvolemj/Screen+Shot+2016-04-19+at+4.47.14+PM.png)

**Comment by emilast** [comment]
Not sure about that. Does it look better if you change an "ERROR" to "WARN"? If so then perhaps I can find another mapping that is mor compatible with different themes.

I also notice from your screen dump that dates with time zones are not highlighted correctly. I'll add an issue about that.
