### ISSUE TITLE
Feature: Apply default color after custom pattern

### ISSUE THREAD

**Issue by quangkieu** [emilast/vscode-logfile-highlighter#46]
Hi, Thank for the create great extension and custom highlight.
I would like to suggest feature to apply default highlight after custom highlight
Example 
![image](https://user-images.githubusercontent.com/4308312/36317010-e8263f92-1309-11e8-9ae1-85f0f6e79004.png)
![image](https://user-images.githubusercontent.com/4308312/36317065-0a43c14e-130a-11e8-80f6-7120a93d69ca.png)

As you could see that the custom highlight is work perfectly but you could see the last digit 3 at the end is not highlight by the default color any more like the ones above it.

I would like to ask for either another entry in VSCode settings that would be painted before the default or attribute of custom patterns that for the same purpose
```
    "logFileHighlighter.customLowLevelPatterns": [
        {
            "pattern": "\\* START \\*.*",
            "foreground": "teal"
        }
    ]
```

or

```
    "logFileHighlighter.customPatterns": [
        {
            "pattern": "\\* START \\*.*",
            "foreground": "teal",
            "lowLevel": true
        }
    ]
```

**Comment by emilast** [comment]
It took me a while to understand this, but you mean that you would like to use the custom pattern to set the default color of a line and then let the default highlighting override it where the respective default patterns match?

We'll consider this, but I'm not sure how general this need is or how difficult it would be to implement.

**Comment by HaaLeo** [comment]
I think it cannot be controlled via the vscode api when the default and when the custom syntax highlighting is applied. Maybe a solution to this concrete problem would be to formulate a more specific regex pattern in order to not overwrite numbers. Something like:  

    {
        "pattern": "\\* START \\*.[ =\\w]*",
        "foreground": "teal"
    }

**Comment by emilast** [comment]
@quangkieu, in the latest release 2.5.0 you can now set the background color for a custom pattern. If you don't set the foreground color then it will be taken from the built-in patterns so this might work for you:

```
"logFileHighlighter.customPatterns": [
    {
      "pattern": "\\* START \\*.*",
      "background": "teal"
    }
]
```
HTH.
