### ISSUE TITLE
Update open-vsx version

### ISSUE THREAD

**Issue by cold-nagai** [emilast/vscode-logfile-highlighter#463]
Could you please update the open-vsx.org (VSCodium) version of your extension? 

>Last released
11/7/2020, 19:45:04

**Comment by emilast** [comment]
Well, to continue pushing versions they wanted me to sign some document whose terms I didn't feel comfortable with so I'm afraid that is not a priority at the moment. Also, there were basically no downloads so it didn't feel worth it to spend time on it. I'm sorry if that's inconvenient.
