### ISSUE TITLE
How to disable the default VSCode log highlighting?

### ISSUE THREAD

**Issue by hepiyellow** [emilast/vscode-logfile-highlighter#464]
In the following snapshot, the Blue highlighting is done by VSCode's default grammar for `log` files.

How can I disable them?

<img width="1128" alt="Screenshot 2023-06-08 at 15 54 20" src="https://github.com/emilast/vscode-logfile-highlighter/assets/6338722/13c96d76-707b-4828-b52b-2f0bc3fca2b7">

**Comment by emilast** [comment]
That's a good question. I don't think you can turn the built-in colorizations off per se, but if you don't like the color of constants (which are blue your example), you can override the color and other styling in VS Code's settings file as [described](https://github.com/emilast/vscode-logfile-highlighter#customization) in the readme.

For example:
```json
"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "scope": "log.constant",
            "settings": {
                "foreground": "#d1d1cc"
            }
        }
    ]
},
```
I hope that helps.
