### ISSUE TITLE
Do not provide syntax highlighting to the message

### ISSUE THREAD

**Issue by sandy081** [emilast/vscode-logfile-highlighter#47]
From VS Code #42517

VS Code uses the grammar from here, to syntax colour the log files. It is very nice, but the colouring sometimes appears random (see below). Is it possible to colour only the header but not the body of the message?

![image](https://user-images.githubusercontent.com/172399/35580870-8d344952-05ea-11e8-9dff-c5fb860ecf9c.png)

**Comment by HaaLeo** [comment]
This behavior changed with release [2.1.0](https://github.com/emilast/vscode-logfile-highlighter/blob/master/CHANGELOG.md#210---14-feb-2018). Now file system paths are highlighted generally and `-` was added as valid delimiter of namespaces.  
Maybe that is a suitable solution for you?

**Comment by emilast** [comment]
Hopefully this is not a problem anymore. I'm closing this now but feel free to reopen it if there are still cases that are highlighted badly.

**Comment by sandy081** [comment]
Yeah it works. Thanks/
