### ISSUE TITLE
Extension not working on big files

### ISSUE THREAD

**Issue by azsde** [emilast/vscode-logfile-highlighter#48]
Hello,

I have huge log files (835k+ lines) and this extension seems not to work with big files.

Is there a reason for this ?

**Comment by emilast** [comment]
This is because of a builtin behavior in VS Code (https://code.visualstudio.com/updates/v1_15#_large-file-support). I assume they enforce a file size limit for performance reasons. It would be nice if it could be changed via configuration but you can't AFAIK.
