### ISSUE TITLE
Connect paths when separated only by words and spaces

### ISSUE THREAD

**Issue by sandy081** [emilast/vscode-logfile-highlighter#50]
From https://github.com/Microsoft/vscode/issues/44808

Spaces break the colouring:

![image](https://user-images.githubusercontent.com/9205389/36839587-c7f1b434-1d42-11e8-8daf-0109ed35ede6.png)

**Comment by emilast** [comment]
Yes, they do.

But how could the highlighting know if a space character should be included in a path or is used as a separator? I've seen both ;-)

**Comment by emilast** [comment]
I decided to remove file system path highlighting in the latest version since it was hard to get it right in all cases.

**Comment by sandy081** [comment]
Thanks for letting us know.

**Comment by sandy081** [comment]
@emilast Looks like file paths are still being highlighted. Please check this

![image](https://user-images.githubusercontent.com/10746682/44653049-ea6aa100-a9ed-11e8-99f0-deb23639053e.png)

**Comment by emilast** [comment]
I see. It's not actually a path that is highlighted but a namespace according to the syntax grammar, although that is a mistake in this case. I'll see if I can experiment with the regexes so it doesn't do this when surrounded by slash or backslash.
