### ISSUE TITLE
Disable path\url highlighting 

### ISSUE THREAD

**Issue by disshishkov** [emilast/vscode-logfile-highlighter#51]
How can I disable the path and url highlighting?

**Comment by emilast** [comment]
Well, currently you can't. Would you need a switch to turn them off?

If you're desperate you can of course manually edit the language definition file where it's installed but manual changes like that will obviously be overwritten when upgrading to a new version.

Paths:
Windows: `%USERPROFILE%\.vscode\extensions\emilast.logfilehighlighter-2.1.1\syntaxes\log.tmLanguage`
Mac/Linux: `$HOME/.vscode/extensions/emilast.logfilehighlighter-2.1.1/syntaxes/log.tmLanguage`

**Comment by disshishkov** [comment]
Yes, the switch will be nice, because now url and path highlighter is too greedy and highlight what I don't want.

**Comment by emilast** [comment]
I decided to remove the highlighting of paths in the latest version, so this won't be a problem anymore.
