### ISSUE TITLE
square brackets highlight

### ISSUE THREAD

**Issue by berot3** [emilast/vscode-logfile-highlighter#518]
https://github.com/emilast/vscode-logfile-highlighter/blob/bcbc67118d23fb709c22d5a5420f4547870277c3/README.md?plain=1#L133

this is supposed to match text _within_ square brackets?

for me it highlights everythign between too, if there is more than one pattern per line. for me this works instead:

```
            "pattern": "\\[(.*?)\\]",
```

<img width="490" alt="image" src="https://github.com/emilast/vscode-logfile-highlighter/assets/52616/ee4c760b-6e64-47c1-876b-a94f5a4d9519">

---

in comparison to suggestion from the README

<img width="446" alt="image" src="https://github.com/emilast/vscode-logfile-highlighter/assets/52616/c8b9662a-d33d-4aae-ab5b-0db9a00f7e4a">

**Comment by emilast** [comment]
Thank you, I will update the readme.
