### ISSUE TITLE
Highlight brackets

### ISSUE THREAD

**Issue by rdsanchezdu** [emilast/vscode-logfile-highlighter#560]
Hi, I would like to have the option to see highlighted the brackes, so I use the below settings,  but then the extension stopped working. 
"files.associations": {
        "*.log": "text"
    },
 "workbench.colorCustomizations": {
        "editorBracketMatch.background": "#000000",
         "editorBracketMatch.border": "#00ff00"
 }

**Comment by emilast** [comment]
You have disabled the extension for *.log files with your **files.associations** settings. This is how you associate file extensions to Log File Highlighter:

```
"files.associations": {
    "*.log.*": "log"
},
```
