### ISSUE TITLE
Date format add MM-DD hh:mm:ss

### ISSUE THREAD

**Issue by ktasl** [emilast/vscode-logfile-highlighter#59]
Dear sir ,
Can we custom the date format by our own, or add this date format in this plug-in, please.
Thank you.

**Comment by emilast** [comment]
Hi. This is supported by using custom highlighting patterns (https://github.com/emilast/vscode-logfile-highlighter#defining-custom-highlighting-patterns).

The following is an example pattern for coloring your date variant:

```json
"logFileHighlighter.customPatterns": [
  {
    "pattern": "\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d",
    "foreground": "green"
  }
]
```

Note that this will only affect the syntax highlighting, not duration calculations.

HTH.

**Comment by emilast** [comment]
I'll close this now as there's not been any further feedback.
