### ISSUE TITLE
Visualization of Time Duration and Progress support "us"

### ISSUE THREAD

**Issue by Ericwln** [emilast/vscode-logfile-highlighter#594]
Can you support defining the unit of this timestamp statistics as ms or us?
example：[2023-09-26 18:24:17.035169]----------[2023-09-26 18:24:17.055344]
example ms/unit：23.567ms
example us/unit：23567us

**Comment by emilast** [comment]
Related (duplicate?) issue: #65.

**Comment by emilast** [comment]
Microsecond precision support is now implemented, in version 3.3.0.
