### ISSUE TITLE
Issue - highlighting of GUIDs in log message

### ISSUE THREAD

**Issue by ivoh** [emilast/vscode-logfile-highlighter#6]
Awesome tool.

Unfortunately it cannot recognize GUID correctly. It colorizes only the parts that are completely number.

E.g. if the log line contains:
ParamId=70afd445-5948-4597-9951-373d336e1627
then the colorized parts are only (bold):
ParamId=70afd445-**5948**-**4597**-**9951**-373d336e1627
but it should be
ParamId=**70afd445-5948-4597-9951-373d336e1627**
or none.

**Comment by emilast** [comment]
Thanks for pointing this out. I'll fix it in the next release.
