### ISSUE TITLE
Not seeing any formatting?

### ISSUE THREAD

**Issue by mikeerickson** [emilast/vscode-logfile-highlighter#60]
I have created a simple log interface as follows

```
2018-08-29 10:27:56 INFO Finish .test
2018-08-29 10:27:56 INFO Finish .lint:js-fix
2018-08-29 10:27:56 INFO Finish .lint:js
2018-08-29 10:27:56 INFO Finish .lint
2018-08-29 10:27:56 INFO Finish .test:unit
2018-08-29 10:27:56 INFO Finish .build
```

But when I view the log file in VSCode, it does not have formatting as it appears in your screenshots?

Is this because the date format is different?

Here is a screenshot of what I see

![image](https://user-images.githubusercontent.com/183153/46248857-0d64e800-c3d4-11e8-904b-afe22b553f39.png)

Must I need to configure the various colors myself, or are there sensible defaults (I am fine with the appearance of your screenshot)

**Comment by emilast** [comment]
The default colors are given by the color theme selected in VS Code so it's expected to differ for users with different themes. However, the colors can be customized to override the defaults as documented here: https://github.com/emilast/vscode-logfile-highlighter#customizing-the-colors

**Tip**: Use the **Developer: Inspect TM Scopes** command from the command palette (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>) to see the current lexical scopes the cursor is in).

**Comment by mikeerickson** [comment]
Ah, so chances are, my theme (Night Owl) don’t have defined colors.  I will take a closer look, thanks for information.

**Comment by mikeerickson** [comment]
@emilast Heck, just providing me with the TIP is gold :-)   I have always wondered how this was done!
