### ISSUE TITLE
Extend support to include log.header and log.footer

### ISSUE THREAD

**Issue by mikeerickson** [emilast/vscode-logfile-highlighter#62]
I use these command often for "group" logging output.  I would like to be able to colorize these log types as well.

Would you consider adding `log.header` and `log.footer`

If you are keen to allowing these commands, I would be happy to submit a PR for it (if you are too busy)

Thanks in advance for your consideration

**Here is a sample of my log with these items**

```
2018/09/10 14:27:40 PM HEADER ==> starting process
2018/09/10 14:27:40 PM INFO Start build
2018/09/10 14:27:40 PM INFO Finish build
2018/09/10 14:27:40 PM FOOTER ==> ending process
2018/09/10 14:27:45 PM HEADER ==> starting process
2018/09/10 14:27:45 PM INFO Start test:script
2018/09/10 14:27:45 PM INFO Finish test:script
2018/09/10 14:27:45 PM FOOTER ==> ending process
```

**Comment by emilast** [comment]
Well, those keywords feel a bit non-standard to me. Have you seen them used elsewhere?

You can always add custom keywords to your personal settings (https://github.com/emilast/vscode-logfile-highlighter#defining-custom-highlighting-patterns), maybe that would be enough?

**Comment by mikeerickson** [comment]
Yep, that will do just fine!  Thanks
