### ISSUE TITLE
Timestamp color include AM/PM format

### ISSUE THREAD

**Issue by mikeerickson** [emilast/vscode-logfile-highlighter#63]
What would you suggest I could do to include AM/PM in color formatting? I have tried to add custom pattern, but it is now helping

```json
"logFileHighlighter.customPatterns": [
    {
      "pattern": "AM",
      "foreground": "#AFF2C5"
    },
    {
      "pattern": "PM",
      "foreground": "#AFF2C5"
    }
]
```

![image](https://user-images.githubusercontent.com/183153/48320363-24e7e100-e5ce-11e8-80cf-cae93a3dd69f.png)

**Comment by HaaLeo** [comment]
Try the following:
```JSON
"logFileHighlighter.customPatterns": [
    {
      "pattern": "\\bAM",
      "foreground": "#AFF2C5"
    },
    {
      "pattern": "\\bPM",
      "foreground": "#AFF2C5"
    }
]
```

**Comment by mikeerickson** [comment]
@HaaLeo Works like a charm, thanks.   Out of curiosity, what does the `\\b` do?

**Comment by emilast** [comment]
`\\b` matches a word boundary. But I have to confess that I don't understand how that helps in this case, so I'll leave that explanation for @HaaLeo :-)

**Comment by HaaLeo** [comment]
When a custom pattern consists only of letters it is wrapped before the regex is built ([Reference](https://github.com/emilast/vscode-logfile-highlighter/blob/master/src/CustomPattern.ts#L40)). This built regex does not match `... PM]`. However when the custom pattern consitst of characters different than letters (in this case `\\`) the regex is built directly with the custom pattern without wrapping.

**Comment by mikeerickson** [comment]
@haaleo thanks for clarification. I am not very strong with regex (it is always something I wish I knew more, but never seem to allocate time to learn)
