### ISSUE TITLE
Microsecond (custom) precision in selected logs duration

### ISSUE THREAD

**Issue by R2RT** [emilast/vscode-logfile-highlighter#65]
Hi,

I am really impressed how simple and useful is elapsed time calculation.
Although I am working on some real-time system and my logs have microsecond precision, which gets duration rounded down into "0ms". I'd would be really nice it microsecond (custom) precision could be enabled on demand.

**Comment by emilast** [comment]
Thank you for reporting this. I can see that it would be useful to show microsecond durations when needed. I'll look into it, but it might be a little while before I get the time to do it.

**Comment by emilast** [comment]
Microsecond precision support is now implemented, in version 3.3.0.
