### ISSUE TITLE
Highlighting not working on log

### ISSUE THREAD

**Issue by TomYeoman** [emilast/vscode-logfile-highlighter#66]
Hi thanks for developing the extension!

I'm unable to view my winston generated logs using this - Is the object supported or is there some configuration I've missed in order to support this?

![image](https://user-images.githubusercontent.com/14075632/54833870-d4d50580-4cb6-11e9-89c4-c53b188a3346.png)

**Comment by emilast** [comment]
This is a JSON log file and is not fully supported. Most values in your file are enclosed in quotes so will be parsed as strings by the extension, which is probably not what you want. However, you might get some reasonable results by using custom patterns such as the following, which marks error-levels as red by looking for `level`-properties with the value `'error'`:

```
        {
            "pattern": "(?<='level':\\s*')error(?=')",
            "foreground": "red"
        },
```

Hope this helps at least a bit.

/Emil
