### ISSUE TITLE
Change line background color

### ISSUE THREAD

**Issue by alejandrofortes** [emilast/vscode-logfile-highlighter#67]
Hi!

First of all, thank you for developing this great extension.

I wonder if it is possible to change the background color of a line based on a certain pattern.

I think it allows you to see the exceptions more visually.

Thanks in advance

**Comment by NightOwlCoder** [comment]
One more for this request.
We should be able to just add `background` to the already possible configuration:
```
    "logFileHighlighter.customPatterns": [
        {
            "pattern": "\\[LocationService\\]",
            "foreground": "orange"
        },
        {
            "pattern": "\\[\\w\\] \\[App\\] App created",
            "foreground": "#ff7d00",
            "background": "#cccccc",
        }
    ],```
