### ISSUE TITLE
Apply colours to the whole block / line

### ISSUE THREAD

**Issue by moifmurphy** [emilast/vscode-logfile-highlighter#72]
Hello,

I'm a big fan of this extension, it's helped me locate stack traces in log files.

However, I was wondering if it's possible to apply the grammar token changes so that the whole line is coloured or even the relevant block?

For example, log.debug highlights the word but how do I apply that colour to the entire line?

**Comment by emilast** [comment]
Well, you can't change the regex expressions that are built-in to the extension (unless you fork it of course). But you can define custom highlighting expressions (https://github.com/emilast/vscode-logfile-highlighter#customizing-the-colors) to do something similar.

For example, to highlight the entire line for lines that contain the text `debug`, you could add the following to your preferences:

```
"logFileHighlighter.customPatterns": [
	{
		"pattern": ".*debug.*",
		"background": "#054405"
	}
]
```
