### ISSUE TITLE
How to add new patterns to predefined levels

### ISSUE THREAD

**Issue by bobatsar** [emilast/vscode-logfile-highlighter#76]
I would like to highlight an android logcat file.
The lines are [like here.](https://developer.android.com/studio/images/debug/logcat_2x.png)

There are levels D/, I/, W/, E/, V/.
Is it possible to add these patterns?

Or as a workaround. How can I add those as custom patterns to e.g. log.error, log.debug, ...

**Comment by emilast** [comment]
Yes, that's a good idea, I'll look into it.

In the meantime you should be able to get it working reasonably well using custom patterns along these lines:

```

"logFileHighlighter.customPatterns": [
    {
        "pattern": "E/\\w+",
        "foreground": "#af1f1f",
        "background": "blue"
    }
]
```
