### ISSUE TITLE
How do you apply this to the debug console?

### ISSUE THREAD

**Issue by bsutton** [emilast/vscode-logfile-highlighter#78]
I wan't to apply this color coding to the debug console ouput but I couldn't see a way to make this possible.?

**Comment by emilast** [comment]
No, I'm afraid I don't know either. There might be a MIME type of that panel that I could associate with but I'm not sure. Will think of it and see if I can come up with something.

**Comment by emilast** [comment]
Hi again. I received a similar issue to this one: #104

There was indeed a mime type that could be used but we decided against it, since some of the coloring didn't make much sense in normal debug output. Do you agree or do you still have a use case where this would be useful?

**Comment by bsutton** [comment]
Essentially i want to be able to colour code log messages using ANSI escaped sequences to make debug output easier to read. I also want stack traces I generate to be clickable.

**Comment by emilast** [comment]
Regarding ANSI colors, others have requested that as well (#57). Will see if I get time off to investigate how it could be solved, but it won't likely happen in the near future, I'm afraid.

Clickable stack traces are obviously a useful thing, but it's not something that I have currently planned to add.

**Comment by bsutton** [comment]
``i have to say that both of these items would provide a significant usability enhancement.

**Comment by emilast** [comment]
Yes, if someone was to create a PR with these features, it would stand a good chance of being approved.
