### ISSUE TITLE
Colors in clipboard

### ISSUE THREAD

**Issue by micharaze** [emilast/vscode-logfile-highlighter#79]
It would be a nice feature if the copied log elements are in the clipboard with the displayed color. Currently when I copy lines from log, the colors in the clipboard are not the same like in the log file displayed. 

My log looks with the package like this:
![image](https://user-images.githubusercontent.com/26977019/63139882-8122da00-c012-11e9-8c8e-327c41789b64.png)

Copied in for example Word:
![image](https://user-images.githubusercontent.com/26977019/63139946-b8918680-c012-11e9-8d64-545ff995a01e.png)

**Comment by emilast** [comment]
I just tested and this seems to work correctly now. Closing the issue.
