### ISSUE TITLE
Add Xorg Error Specifiers

### ISSUE THREAD

**Issue by stellarpower** [emilast/vscode-logfile-highlighter#80]
Hi,

I was trying to modify to add support for XOrg errors, e.g. (EE), (II), (WW). I've modified the file however the build fails so; I can run the unit tests successfully, but the integration tests fail. Would you like the test errors, or shall I submit a pull request with the (untested) modifications?

Thanks

**Comment by emilast** [comment]
That's OK, the integrations tests have started failing for some reason. I didn't write them in the first place and have not prioritized fixing them.

So feel free to submit your PR and I'll have a look.
