### ISSUE TITLE
How to color multiline sections ?

### ISSUE THREAD

**Issue by d-faure** [emilast/vscode-logfile-highlighter#87]
I tried using custom settings but couldn't define highlighting for multiline log sections such as dumped SQL request. How could I get this working?

**Comment by emilast** [comment]
You can define a custom highlighting pattern which matches several lines:
```
"logFileHighlighter.customPatterns": [
	{
		"pattern": "b[\r\n]*c",
		"background": "red"
	}
]
```
But apparently only the match on the first line is highlighted, which is a bug.

**Comment by urielzen** [comment]
@emilast Hi friend, just wondering if the work on this extension is still ongoing? This would be a nice bug to fix, if possible. Thanks for your efforts!

**Comment by emilast** [comment]
No progress so far, but I'll be happy to accept a PR if someone gets around to fix it :-)

**Comment by emilast** [comment]
I have recently been a bit more active in the development of this extension and have finally added support for multiline custom patterns in the form of the new **patternFlags** option in version 3.1.0 that was just released.

[Here's an example](https://github.com/emilast/vscode-logfile-highlighter/tree/3.1.0?tab=readme-ov-file#multiline-custom-patterns) that uses the 's' flag to make a pattern multiline.

I hope this helps.
