### ISSUE TITLE
Not Working w/Insiders Version

### ISSUE THREAD

**Issue by dprice** [emilast/vscode-logfile-highlighter#9]
I tried to install using Code Insiders version but received this error message:

**Couldn't find a compatible version of Log File Highlighter with this version of Code.**

Are there plans to make it compatible with the Insiders version?

Thanks,
Derek

Here is my version:
[Window Title]
Visual Studio Code - Insiders

[Main Instruction]
Visual Studio Code - Insiders

[Content]

Version 1.6.0-insider
Commit 602155bb781f509c7a4ddcd700b57cb9b9f5286d
Date 2016-10-01T00:36:55.469Z
Shell 1.3.7
Renderer 52.0.2743.82
Node 6.5.0

[OK]

**Comment by emilast** [comment]
Thanks for pointing this out. There's nothing in the extension that keeps it from working with the Insiders version, must be something in the manifest. I'll change it in the next release, hoping it will fix the problem. 

For now, you can install the extension in the "standard" VS Code and then manually copy it from `%USERPROFILE%\.vscode\extensions` into `%USERPROFILE%\.vscode-insiders\extensions`. Worked for me.

/Emil

**Comment by dprice** [comment]
I copied the extension over from Code to Insiders and it worked, but the performance is horrible for some reason. I tried a relatively small log file (7KB) and I can watch the syntax highlight go line by line in Insiders. I opened a 7MB in Code and it was almost instantaneous. Any ideas?

**Comment by emilast** [comment]
I'm afraid that I have no idea...
