### ISSUE TITLE
Incompatible with the Material Theme

### ISSUE THREAD

**Issue by RintFosk** [emilast/vscode-logfile-highlighter#90]
I've installed the Material Theme and the Logfile highlighter, both in the latest version. The problem is when both plugins are enabled, the lines in my log file failed to have colours applied. After I disabled the Material Theme the colours then are correctly applied. 

Is there any way to use both plugins at the same time?

**Comment by RintFosk** [comment]
The problem is solved, should have read the manual more carefully. 

The colours that the Logfile Highlighter uses are directly dependent on the colour theme that the user chose to use, which means that using the Material Theme would make the highlighting not as seen as the demonstration gave on the extension page.

There's no method to easily override all the colours to the "intended" colours as the demonstration show, however the colours can be customized and override the theme colour with the tutorial in the manual:

> To override the color for one of these, use the editor.tokenColorCustomizations user setting, which was introduced in Visual Studio Code 1.15. Here's an example that forces errors to be red and bold and warnings to be orange, regardless of what color theme is used:

`"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "scope": "log.error",
            "settings": {
                "foreground": "#af1f1f",
                "fontStyle": "bold"
            }
        },
        {
            "scope": "log.warning",
            "settings": {
                "foreground": "#f4ad42",
                "fontStyle": ""
            }
        }
    ]
}`

...with each single of these scopes manually changed:

`log.constant
log.date
log.verbose
log.debug
log.error
log.exception
log.info
log.string
log.exceptiontype
log.warning`

**Comment by emilast** [comment]
You're right, that is the main use case for the tokenColorCustomizations setting. Happy to hear it solved your problem.
