### ISSUE TITLE
The custom color is not applied

### ISSUE THREAD

**Issue by namnx87** [emilast/vscode-logfile-highlighter#92]
Hello,

Somehow, the custom pattern I configured is applied only on some workspace, not everywhere. 
Non working case
![image](https://user-images.githubusercontent.com/4465335/71753669-8da1b500-2e83-11ea-9258-6e20e6176551.png)

Working case:
![image](https://user-images.githubusercontent.com/4465335/71753637-74006d80-2e83-11ea-936b-c8251b98b25d.png)

I don't have any extra setting for these workspaces. Do you have any idea why ?
Thanks

**Comment by namnx87** [comment]
I notice that the status bar color are different in working case and non-working case, maybe it is the root cause.

**Comment by emilast** [comment]
Not sure why this happens. If you share your config, I'll have a look at it.

**Comment by namnx87** [comment]
Here is my settings.json:
`{
    "editor.minimap.enabled": false,
    "java.errors.incompleteClasspath.severity": "ignore",
    "python.pythonPath": "C:\\Users\\xnguyen\\AppData\\Local\\Programs\\Python\\Python37\\python.exe",
    //"python.pythonPath": "C:\\cygwin64\\bin\\python2.7.exe",
    "window.zoomLevel": 1,
    "python.jediEnabled": false,
    // to fix 'Timeout waiting for debugger connections'
    "python.terminal.activateEnvironment": false,
    "terminal.integrated.shell.windows": "C:\\windows\\System32\\cmd.exe",
    "editor.stopRenderingLineAfter" : -1,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "java.home": "C:\\Java\\jdk1.8.0_51",
    "macros": {
        "commentDown": [
            "editor.action.copyLinesDownAction",
            "cursorUp",
            "editor.action.addCommentLine",
            "cursorDown"
        ]
    },
    "files.associations": {
        "*.txt": "log",
        "*.log": "log",
        "*.log.*": "log"
    },
    "python.linting.pylintEnabled": true,
    "workbench.colorTheme": "Visual Studio Dark",
    "breadcrumbs.enabled": false,
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "logFileHighlighter.customPatterns": [
        {
            "pattern": "WARN",
            "foreground": "yellow"
        },
        {
            "pattern": "ERR",
            "foreground": "red"
        }
    ],
    "peacock.favoriteColors": [
        {
            "name": "Angular Red",
            "value": "#b52e31"
        },
        {
            "name": "Auth0 Orange",
            "value": "#eb5424"
        },
        {
            "name": "Azure Blue",
            "value": "#007fff"
        },
        {
            "name": "C# Purple",
            "value": "#68217A"
        },
        {
            "name": "Gatsby Purple",
            "value": "#639"
        },
        {
            "name": "Go Cyan",
            "value": "#5dc9e2"
        },
        {
            "name": "Java Blue-Gray",
            "value": "#557c9b"
        },
        {
            "name": "JavaScript Yellow",
            "value": "#f9e64f"
        },
        {
            "name": "Mandalorian Blue",
            "value": "#1857a4"
        },
        {
            "name": "Node Green",
            "value": "#215732"
        },
        {
            "name": "React Blue",
            "value": "#00b3e6"
        },
        {
            "name": "Something Different",
            "value": "#832561"
        },
        {
            "name": "Vue Green",
            "value": "#42b883"
        }
    ],
    "workbench.iconTheme": "material-icon-theme"
}`

**Comment by namnx87** [comment]
Issue is not occurred anymore.

**Comment by emilast** [comment]
Glad to hear it. It was probably related to #91.
