### ISSUE TITLE
Remove `log` from language menue

### ISSUE THREAD

**Issue by ArbiterOfBuffoonery** [emilast/vscode-logfile-highlighter#96]
When I type "Change Language Mode" in the command pallet, there is a `log` entry and a `log file` entry. I would like to remove one so that there is only the entry for this plugin.
![double_log_entry](https://user-images.githubusercontent.com/13684150/75077289-48d3eb00-54d0-11ea-917c-f64f363bdd15.gif)

**Comment by emilast** [comment]
The first language (`log`) is built in into VS Code, based on an earlier version of the LogFileHIghlighter extension and there is no way to remove it, hid it or overwrite it as far as I know. The one called `Log File` is the extension's language definition and is of course the preferred one when the extension is installed.
