### ISSUE TITLE
Cannot get the extension to work

### ISSUE THREAD

**Issue by oganexon** [emilast/vscode-logfile-highlighter#97]
Despite my best efforts, I can't get the extension to work.
It's still the default highlighter. Or is that normal behavior? Warn messages aren't even colored.
I deactivated all the extensions, checked that I was in "Log File" mode but nothing helped.

![](https://i.imgur.com/3ezGgrk.png)
![](https://i.imgur.com/4ZWeAGM.png)

I'm on:
Version: 1.43.2 (user setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by emilast** [comment]
What is it that's not working? The colors depend on your color theme so if the colors are not what you expect you may have to override them, which is described in the readme.

You can also try to view our sample log file to see if coloring works: https://raw.githubusercontent.com/emilast/vscode-logfile-highlighter/master/content/Test.log

If you select two lines or more that starts with dates then the duration between the first and last date should be shown in the status bar.

**Comment by oganexon** [comment]
Thanks, I should have tested that file earlier.
I thought the extension didn't work because the "warn:" pattern wasn't highlighted.
