### ISSUE TITLE
Red warnings and yellow errors?

### ISSUE THREAD

**Issue by brianary** [emilast/vscode-logfile-highlighter#98]
I've got a log that has lines that start:

```log
WARN  2020-04-01 17:21:08,243 
WARN  2020-04-01 17:21:08,243 
ERROR 2020-04-01 17:21:09,255 
ERROR 2020-04-01 17:21:09,255 
```
and they are rendered using red for warnings and yellow for errors, which doesn't match the screenshots for the extension: 

![image](https://user-images.githubusercontent.com/8332839/78279081-db05e080-74cb-11ea-8687-f9c8ea9c6a97.png)

**Comment by emilast** [comment]
The colors are taken from the active color theme by default so they harmonize with background colors etc. To override the colors, follow these instructions: https://github.com/emilast/vscode-logfile-highlighter#customizing-the-colors
